services:
  - type: web
    name: nashmi-ride
    env: node
    plan: free
    region: frankfurt
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: ADMIN_KEY
        value: darbak-2026
